In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [5]:
cancer_data=pd.read_csv('data.csv')

In [6]:
cancer_data.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [7]:
cancer_data.shape

(569, 33)

In [8]:
cancer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [11]:
df=pd.DataFrame(cancer_data)

In [15]:
df['diagnosis'].value_counts().sum

<bound method Series.sum of diagnosis
B    357
M    212
Name: count, dtype: int64>

In [ ]:
df.isnull().sum()

In [24]:
cancer_data.describe()

                 id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [25]:
label_encode=LabelEncoder()
labels=label_encode.fit_transform(cancer_data['diagnosis'])

cancer_data['target']=labels

cancer_data.drop(columns='diagnosis',axis=1,inplace=True)

In [27]:
cancer_data.head()

         id  radius_mean  ...  Unnamed: 32  target
0    842302        17.99  ...          NaN       1
1    842517        20.57  ...          NaN       1
2  84300903        19.69  ...          NaN       1
3  84348301        11.42  ...          NaN       1
4  84358402        20.29  ...          NaN       1

[5 rows x 33 columns]

In [29]:
cancer_data['target'].value_counts().sum

<bound method Series.sum of target
0    357
1    212
Name: count, dtype: int64>

In [30]:
cancer_data.groupby('target').mean()

                  id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
target                             ...
0       2.654382e+07    12.146524  ...                 0.079442          NaN
1       3.681805e+07    17.462830  ...                 0.091530          NaN

[2 rows x 32 columns]

Summary:

1> No missing values
2> all are continuous value except target
3>mean is more than median so it is rightly skewed
4>Mean of most feature are clearly larger for malignant cases compared to benign cases